$ErrorActionPreference='Stop'
$root='C:\Users\USER\Documents\Codex\Barry'
$s=Get-Content -Raw (Join-Path $root 'secrets\development-2-elementor-mcp.json')|ConvertFrom-Json
$sec=ConvertTo-SecureString $s.application_password_dpapi;$ptr=[IntPtr]::Zero
try{
 $ptr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($sec);$pw=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
 $pair=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($s.username):$pw"));$h=@{Authorization="Basic $pair"}
 $services="- Choose Service -|`nSolar Panel Repairs`nSolar Panel Servicing`nSolar Battery Add-ons`nElectrical Panel Upgrades`nEV Charger Installs`nOther Solar or Electrical Help"
 function Walk($nodes){foreach($n in $nodes){if($n.widgetType-eq'form'){$n.settings.form_name='Solar Repair Pros Website Enquiry';$n.settings.email_to='info@solarrepairdfw.com';$n.settings.email_subject='New Solar Repair Pros Website Enquiry';$n.settings.email_from_name='Solar Repair Pros Website';foreach($f in $n.settings.form_fields){if($f.field_type-eq'select'){$f.field_label='Choose Service*';$f.field_options=$services}}};if($n.widgetType-eq'social-icons'){$n.settings.social_icon_list=@()};if($n.elements){Walk $n.elements}}}
 function AddSchema($data,$obj){if(-not$obj){return};$json=$obj|ConvertTo-Json -Depth 30 -Compress;$html="<script type=`"application/ld+json`" data-barry-schema=`"final-review`">$json</script>";function FindSchema($nodes){foreach($n in $nodes){if($n.widgetType-eq'html'-and$n.settings.html-like'*data-barry-schema="final-review"*'){return $n};if($n.elements){$r=FindSchema $n.elements;if($r){return $r}}}};$existing=FindSchema $data;if($existing){$existing.settings.html=$html}else{$bytes=[Security.Cryptography.MD5]::Create().ComputeHash([Text.Encoding]::UTF8.GetBytes($json));$id=([BitConverter]::ToString($bytes)-replace'-','').Substring(0,7).ToLower();$w=[pscustomobject]@{id=$id;elType='widget';settings=[pscustomobject]@{html=$html;css_classes='barry-schema-jsonld'};elements=@();widgetType='html'};$data[0].elements+=@($w)}}
 $org='https://dev2.mynewwebsite.co.za/#organization';$area=[pscustomobject]@{'@type'='AdministrativeArea';name='Dallas-Fort Worth, Texas'}
 $schema=@{}
 $svc=@(
  @{id=6637;slug='solar-panel-repairs-dallas-fort-worth';name='Solar Panel Repairs in Dallas-Fort Worth';desc='Diagnosis and repair planning for damaged panels, production drops and recurring solar system faults.';image='solar-repair-pros-solar-repair-dallas-fort-worth-hero-ai-01.webp'},
  @{id=6638;slug='solar-panel-servicing-dallas-fort-worth';name='Solar Panel Servicing in Dallas-Fort Worth';desc='Condition and performance checks for existing solar arrays across Dallas-Fort Worth.';image='solar-repair-pros-solar-panel-servicing-dfw-ai-01-hero.webp'},
  @{id=6639;slug='solar-battery-add-ons-dallas-fort-worth';name='Solar Battery Add-ons in Dallas-Fort Worth';desc='Solar battery planning around existing equipment, backup priorities and electrical capacity.';image='solar-repair-pros-solar-battery-add-on-dfw-ai-01-hero.webp'},
  @{id=6640;slug='electrical-panel-upgrades-dallas-fort-worth';name='Electrical Panel Upgrades in Dallas-Fort Worth';desc='Electrical panel capacity and upgrade planning for solar, batteries and EV charging.';image='solar-repair-pros-electrical-panel-upgrade-dfw-ai-01-hero.webp'},
  @{id=6641;slug='ev-charger-installs-dallas-fort-worth';name='EV Charger Installs in Dallas-Fort Worth';desc='Home EV charger planning around the vehicle, parking location and available electrical capacity.';image='solar-repair-pros-ev-charger-install-dfw-ai-01-hero.webp'} )
 foreach($x in $svc){$url="https://dev2.mynewwebsite.co.za/services/$($x.slug)/";$schema[$x.id]=[ordered]@{'@context'='https://schema.org';'@type'='Service';'@id'="$url#service";name=$x.name;description=$x.desc;url=$url;serviceType=$x.name;provider=@{'@id'=$org};areaServed=$area;image="https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/$($x.image)"}}
 $schema[6217]=[ordered]@{'@context'='https://schema.org';'@type'='ItemList';'@id'='https://dev2.mynewwebsite.co.za/services/#service-list';name='Solar Repair Pros Services';itemListElement=@($svc|ForEach-Object -Begin{$p=0}-Process{$p++;@{'@type'='ListItem';position=$p;name=$_.name;url="https://dev2.mynewwebsite.co.za/services/$($_.slug)/"}})}
 $cities='Dallas','Fort Worth','Arlington','Plano','Frisco','McKinney','Irving','Garland','Denton','Grapevine','Southlake','Flower Mound'
 $schema[6414]=[ordered]@{'@context'='https://schema.org';'@type'='ItemList';'@id'='https://dev2.mynewwebsite.co.za/service-areas/#area-list';name='Solar Repair Pros Dallas-Fort Worth Service Areas';itemListElement=@($cities|ForEach-Object -Begin{$p=0}-Process{$p++;@{'@type'='ListItem';position=$p;item=@{'@type'='Place';name="$_, Texas"}}})}
 $schema[6425]=[ordered]@{'@context'='https://schema.org';'@type'='Blog';'@id'='https://dev2.mynewwebsite.co.za/blog/#blog';name='Solar Repair Pros Solar Advice';description='Practical solar repair and connected electrical guidance for Dallas-Fort Worth property owners.';url='https://dev2.mynewwebsite.co.za/blog/';publisher=@{'@id'=$org}}
 $targets=@(@{id=6217;type='pages'},@{id=6414;type='pages'},@{id=6425;type='pages'},@{id=6637;type='pages'},@{id=6638;type='pages'},@{id=6639;type='pages'},@{id=6640;type='pages'},@{id=6641;type='pages'},@{id=6248;type='elementor_library'},@{id=2805;type='elementor_library'})
 $done=@();$errors=@()
 foreach($t in $targets){try{$url="https://dev2.mynewwebsite.co.za/wp-json/wp/v2/$($t.type)/$($t.id)?context=edit";$p=Invoke-RestMethod $url -Headers $h;$data=$p.meta._elementor_data|ConvertFrom-Json;Walk $data;if($schema.ContainsKey($t.id)){AddSchema $data $schema[$t.id]};$ej=$data|ConvertTo-Json -Depth 100 -Compress;$body=@{meta=@{_elementor_data=$ej}}|ConvertTo-Json -Depth 6;Invoke-RestMethod $url -Method Post -Headers $h -ContentType 'application/json' -Body ([Text.Encoding]::UTF8.GetBytes($body))|Out-Null;$done+=$t.id}catch{$errors+="$($t.id): $($_.Exception.Message)"}}
 $alts=@{6677='Solar Repair Pros white logo';6621='Dallas skyline in the Solar Repair Pros service area';6681='Fort Worth skyline in the Solar Repair Pros service area';6682='Grapevine and Southlake landscape in the Solar Repair Pros service area';6683='Plano and Frisco landscape in the Solar Repair Pros service area';6708='Dallas skyline representing the Solar Repair Pros service area'}
 foreach($id in $alts.Keys){Invoke-RestMethod "https://dev2.mynewwebsite.co.za/wp-json/wp/v2/media/$id" -Method Post -Headers $h -ContentType 'application/json' -Body (@{alt_text=$alts[$id]}|ConvertTo-Json -Compress)|Out-Null}
 foreach($id in 18,17,2,19,16,20){Invoke-RestMethod "https://dev2.mynewwebsite.co.za/wp-json/wp/v2/categories/$id?force=true" -Method Delete -Headers $h|Out-Null}
 Invoke-RestMethod 'https://dev2.mynewwebsite.co.za/wp-json/wp/v2/categories/1' -Method Post -Headers $h -ContentType 'application/json' -Body (@{description='Practical solar repair, maintenance, battery and connected electrical guidance for Dallas-Fort Worth property owners.'}|ConvertTo-Json -Compress)|Out-Null
 $rep=@{company_or_person='company';company_name='Solar Repair Pros';company_logo='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/Solar-Repair-Pros-Logo-small.png';company_logo_id=6602}|ConvertTo-Json -Compress;Invoke-RestMethod 'https://dev2.mynewwebsite.co.za/wp-json/yoast/v1/configuration/site_representation' -Method Post -Headers $h -ContentType 'application/json' -Body $rep|Out-Null
 $soc=@{facebook_site='';twitter_site='';other_social_urls=@()}|ConvertTo-Json -Compress;Invoke-RestMethod 'https://dev2.mynewwebsite.co.za/wp-json/yoast/v1/configuration/social_profiles' -Method Post -Headers $h -ContentType 'application/json' -Body $soc|Out-Null
 try{Invoke-RestMethod 'https://dev2.mynewwebsite.co.za/wp-json/elementor/v1/cache' -Method Delete -Headers $h|Out-Null}catch{}
 [pscustomobject]@{updated=$done;errors=$errors;categories_removed=6;schema_pages=@($schema.Keys)}|ConvertTo-Json -Compress
}finally{if($ptr-ne[IntPtr]::Zero){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)}}
