$ErrorActionPreference = 'Stop'
$outDir = $PSScriptRoot
$logo = @{ id = 6602; url = 'https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/Solar-Repair-Pros-Logo-small.png'; alt = 'Solar Repair Pros Dallas Fort Worth logo'; source = 'library'; size = 'full' }
$orange = '#ed5e22'
$light = '#FFF4EF'

$services = @(
  @{
    key='servicing'; post=6638; h1='Solar Panel Servicing in Dallas-Fort Worth'; intro='Solar panel servicing helps property owners understand the condition of an existing system before a small concern becomes harder to trace. Solar Repair Pros checks visible panel condition, mounting, cable management and available performance information across Dallas-Fort Worth.';
    eyebrow='SERVICE WARNING SIGNS'; section='When Your Solar Array Is Due for a Closer Look'; lead='Servicing is most useful when there is a repeatable change, a visible condition concern or a clear reason to establish a new performance baseline.';
    cards=@(
      @('Gradual Production Change','A steady shift from the array''s usual pattern can justify a review of soiling, shading, connections and visible equipment condition.','fas fa-chart-line'),
      @('Debris or Heavy Soiling','Leaves, bird activity and stubborn surface buildup can affect particular modules and may also hide damage that is difficult to judge from the ground.','fas fa-solar-panel'),
      @('Loose Cable Management','Sagging or exposed cable runs, displaced clips and movement near connectors should be assessed before weather and roof contact make the issue worse.','fas fa-plug'),
      @('No Recent System Review','An older array with limited monitoring history can benefit from a documented condition check, especially before roof work or another system change.','fas fa-clipboard-check'));
    approachEye='OUR SERVICING APPROACH'; approachTitle='Solar Panel Servicing Built Around the Existing System'; approachSub='Record the condition, compare the information, explain the next step'; approach=@(
      '<strong>Start with context:</strong> System age, monitoring history, recent roof work and the owner''s observations shape the inspection priorities.',
      '<strong>Check visible condition:</strong> Accessible panels, frames, mounting, cable management and surrounding site conditions are reviewed without assuming every output change is a fault.',
      '<strong>Document useful findings:</strong> The customer receives a clear explanation of observed concerns and whether cleaning, repair, monitoring or specialist testing is the sensible next step.');
    trustEye='WHY PLANNED CHECKS HELP'; trustTitle='Servicing Gives Future Repair Decisions Better Context'; trustSub='A useful baseline is more valuable than a vague clean bill of health'; trust=@(
      '<strong>Compare like with like:</strong> Weather, season and shading should be considered when output periods are compared.',
      '<strong>Separate maintenance from repair:</strong> Surface buildup, vegetation and cable management concerns do not always require equipment replacement.',
      '<strong>Plan around other work:</strong> A condition record can help before roofing, electrical upgrades, battery planning or property changes.');
    scenarios=@(
      @('Older Array With Limited Monitoring in Dallas','<strong>Representative scenario:</strong> A homeowner has an established array but little historical data. The servicing visit records current visible condition, checks accessible cable management and reviews whatever inverter or monitoring information is available. The result is a practical baseline rather than a promise that every hidden component is fault-free.'),
      @('Debris Buildup at a Fort Worth Property','<strong>Representative scenario:</strong> Leaves and bird activity collect around part of an array. The assessment considers safe access, whether the buildup is localized and whether there are nearby frame, wiring or drainage concerns. The recommendation distinguishes safe cleaning needs from faults that deserve testing or repair.'),
      @('Condition Check Before Roof Work in Plano','<strong>Representative scenario:</strong> Planned roof maintenance creates a need to document the solar equipment first. Photos, visible mounting condition and cable routes help the owner discuss responsibilities with the roofing and solar teams and identify any existing concerns before work begins.'),
      @('Seasonal Output Change in Arlington','<strong>Representative scenario:</strong> Production appears lower than expected during part of the year. The review considers shade movement, temperature, soiling and monitoring comparisons before treating the change as failed hardware. Any recurring anomaly can then be referred for targeted diagnosis.'));
    relatedIntro='Servicing can reveal a repair question, a storage planning need or an electrical constraint. These related services explain the next step without turning routine observations into unnecessary upgrades.';
    authority='Solar Performance Should Be Compared With Weather, Shade and System History'; authorityCopy='<p>Solar output naturally changes with weather, temperature and seasonal shading. The U.S. Department of Energy''s <a href="https://www.energy.gov/energysaver/homeowners-guide-going-solar" target="_blank" rel="noopener">Homeowner''s Guide to Going Solar</a> provides general system background. A useful service review combines that context with the condition observed at the property.</p>';
    faqTitle='Questions About Solar Panel Servicing'; faqLead='Straight answers for Dallas-Fort Worth owners planning a condition or performance review.';
    qs=@('How often should an existing solar array be checked?','Does solar panel servicing always include cleaning?','What information should I provide before the visit?','Can servicing confirm that every component is fault-free?','Should I arrange a solar check before roof work?');
    ans=@('There is no single interval that suits every system. Age, site conditions, monitoring alerts, roof access and recent weather all matter. A check is particularly useful after a noticeable change, visible damage or work near the array.','Not automatically. The need and safe method depend on the type of buildup, roof access, manufacturer guidance and whether cleaning could affect wiring or damaged modules. The condition should be assessed before a method is chosen.','Share recent production graphs, alert history, equipment information and any dates when performance or site conditions changed. Photos taken safely from the ground can also help prepare for the visit.','No visual service check can prove every hidden electrical component is healthy. It can document accessible condition and identify reasons for targeted monitoring, testing or repair.','Yes, especially when panels, mounting or cable routes may be affected. A before-work condition record helps the property owner coordinate the roofing and solar responsibilities more clearly.');
    img=6617; imgUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-solar-panel-servicing-dfw-ai-01.webp'; hero=6642; heroUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-solar-panel-servicing-dfw-ai-01-hero.webp'; alt='Technician servicing rooftop solar panels in Dallas-Fort Worth'
  },
  @{
    key='battery'; post=6639; h1='Solar Battery Add-ons in Dallas-Fort Worth'; intro='A solar battery add-on should be planned around the existing solar equipment, household loads and the outcome the owner actually wants. Solar Repair Pros helps Dallas-Fort Worth customers frame storage decisions before equipment is selected.';
    eyebrow='BATTERY PLANNING QUESTIONS'; section='What to Clarify Before Adding Solar Storage'; lead='Battery capacity alone does not decide whether a storage plan is suitable. Compatibility, backup priorities, installation space and electrical infrastructure all affect the design.';
    cards=@(
      @('Backup Priorities','Decide which circuits matter during an outage and how long they should run before comparing battery options.','fas fa-battery-three-quarters'),
      @('System Compatibility','The existing inverter, solar layout, monitoring platform and equipment age influence how storage can be integrated.','fas fa-link'),
      @('Installation Location','Temperature, ventilation, clearances, weather exposure and cable routing all matter when a battery location is considered.','fas fa-location-dot'),
      @('Electrical Capacity','Panel space, service capacity, protective equipment and the proposed backed-up loads must be reviewed together.','fas fa-bolt'));
    approachEye='OUR BATTERY PLANNING APPROACH'; approachTitle='Storage Planning That Starts With Loads and Compatibility'; approachSub='Define the job before comparing equipment'; approach=@(
      '<strong>Clarify the goal:</strong> Backup power, solar self-use, time-of-use shifting and future resilience lead to different storage priorities.',
      '<strong>Review the existing system:</strong> Inverter type, array information, monitoring, panel capacity and possible battery locations help narrow compatible approaches.',
      '<strong>Explain the dependencies:</strong> The next step may involve load calculations, manufacturer confirmation, panel work, permits or a specialist design before installation.');
    trustEye='WHY LOAD PLANNING MATTERS'; trustTitle='A Battery Should Be Sized for the Intended Job'; trustSub='Whole-home expectations and essential-load plans are not the same'; trust=@(
      '<strong>Prioritize essential circuits:</strong> Refrigeration, lighting, communications and selected equipment may matter more than trying to back up every load.',
      '<strong>Account for high-demand equipment:</strong> Air conditioning, electric heating, pumps and vehicle charging can change battery and inverter requirements significantly.',
      '<strong>Leave room for real constraints:</strong> Budget, available wall space, equipment compatibility and electrical upgrades can shape a phased plan.');
    scenarios=@(
      @('Essential-Load Backup at a Dallas Home','<strong>Representative scenario:</strong> The owner wants refrigeration, selected lights and internet equipment available during outages. The planning process lists those circuits, checks the existing inverter and panel arrangement, and identifies whether an essential-loads panel or other electrical changes are likely.'),
      @('Existing Solar With an Older Inverter in Fort Worth','<strong>Representative scenario:</strong> A mature solar system was not originally designed for storage. Model information, warranties and manufacturer guidance become important before assuming a modern battery can connect directly. The owner receives a compatibility-led next-step plan.'),
      @('Garage Battery Location in Plano','<strong>Representative scenario:</strong> A garage wall looks convenient, but the assessment still considers clearances, vehicle protection, temperature, ventilation and the cable route to the electrical equipment. If the proposed spot is unsuitable, alternatives can be compared before equipment is ordered.'),
      @('Battery Planning With Future EV Charging in Frisco','<strong>Representative scenario:</strong> The household expects to add an EV charger after storage. Current loads, panel capacity and future charging behavior are discussed together so one project does not create avoidable constraints for the next.'));
    relatedIntro='Battery planning often connects to solar repairs, panel capacity and future EV charging. Reviewing the linked systems together helps avoid incompatible assumptions.';
    authority='Backup Expectations Need a Clear List of Loads and Operating Time'; authorityCopy='<p>Battery energy capacity and power output describe different limits. Start with the circuits you want to support, their likely operating time and any high-demand equipment. The U.S. Department of Energy''s <a href="https://www.energy.gov/energysaver/homeowners-guide-going-solar" target="_blank" rel="noopener">Homeowner''s Guide to Going Solar</a> offers useful general context, while the final storage design must follow the selected equipment and local requirements.</p>';
    faqTitle='Questions About Solar Battery Add-ons'; faqLead='Useful starting points before selecting a battery for an existing Dallas-Fort Worth solar system.';
    qs=@('Can a battery be added to any existing solar system?','How do I decide which circuits should receive backup power?','Will a solar battery run central air conditioning?','Where can a home battery be installed?','Do I need an electrical panel upgrade for a battery?');
    ans=@('Not automatically. Inverter type, system age, equipment compatibility, warranties and the proposed integration method all need review. Some systems support direct options, while others may need additional equipment or a different design.','List the loads that matter during an outage, their power demand and how long you expect to use them. Essential loads are often separated from high-demand or nonessential circuits so the design reflects realistic priorities.','It depends on the air-conditioning starting and running demand, battery power output, inverter design and the other loads operating at the same time. This should be calculated rather than assumed from battery capacity alone.','The location must follow equipment instructions and applicable rules for clearances, temperature, ventilation, weather exposure and physical protection. Cable routing and access for future service also matter.','Possibly. Available breaker space, service capacity, panel condition and the proposed connection method all affect the answer. A panel review is part of responsible storage planning.');
    img=6618; imgUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-solar-battery-addons-dfw-ai-01.webp'; hero=6643; heroUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-solar-battery-addons-dfw-ai-01-hero.webp'; alt='Solar battery equipment planned for a Dallas-Fort Worth home'
  },
  @{
    key='panel'; post=6640; h1='Electrical Panel Upgrades in Dallas-Fort Worth'; intro='An electrical panel upgrade should solve a verified capacity, condition or layout problem. Solar Repair Pros helps Dallas-Fort Worth property owners assess panel space and project requirements connected to solar, batteries and EV charging.';
    eyebrow='PANEL UPGRADE INDICATORS'; section='When New Electrical Equipment May Need Panel Work'; lead='A new solar, storage or charging project does not always require a panel replacement. The existing service, breaker space, condition and calculated loads need to be reviewed first.';
    cards=@(
      @('Limited Breaker Space','A full or crowded panel may need a planned solution before new solar, storage or EV circuits can be added safely.','fas fa-table-cells'),
      @('Capacity Constraints','The service rating and calculated demand must support the proposed equipment and the loads already in the property.','fas fa-gauge-high'),
      @('Visible Condition Concerns','Heat marks, damaged covers, corrosion or loose components are reasons for prompt professional assessment, not DIY investigation.','fas fa-triangle-exclamation'),
      @('Multiple Planned Upgrades','Solar, a battery, electric appliances and EV charging should be considered together so one project does not block another.','fas fa-bolt'));
    approachEye='OUR PANEL PLANNING APPROACH'; approachTitle='Electrical Panel Upgrades Based on the Project Load'; approachSub='Confirm the need before replacing equipment'; approach=@(
      '<strong>Review the existing panel:</strong> Service rating, breaker space, visible condition and connected equipment provide the starting point.',
      '<strong>Define the new loads:</strong> Solar, storage, EV charging and planned electric appliances need to be considered as part of one capacity picture.',
      '<strong>Map the approval path:</strong> Utility coordination, permits, equipment availability and installation sequencing can affect the final scope.');
    trustEye='WHY COORDINATION MATTERS'; trustTitle='Panel Work Sits Between the Utility and New Equipment'; trustSub='The upgrade sequence can matter as much as the equipment choice'; trust=@(
      '<strong>Plan for the actual project:</strong> Breaker space and service capacity are related but not interchangeable constraints.',
      '<strong>Coordinate connected systems:</strong> Solar, batteries and chargers may have manufacturer, utility and interconnection requirements.',
      '<strong>Allow for verification:</strong> Final sizing and installation must follow applicable electrical rules, permits and inspection requirements.');
    scenarios=@(
      @('Full Panel Before EV Charging in Dallas','<strong>Representative scenario:</strong> A homeowner wants a Level 2 charger but the panel has no obvious spare spaces. The assessment reviews service capacity, load information and possible code-compliant alternatives before assuming a complete replacement is the only answer.'),
      @('Solar and Battery Planning in Fort Worth','<strong>Representative scenario:</strong> Storage is being considered alongside an older solar installation. The panel condition, connection method and project sequence are reviewed together so the electrical work supports the final equipment design.'),
      @('Visible Heat Marking at an Arlington Property','<strong>Representative scenario:</strong> Discoloration is noticed near part of the panel. The owner is advised not to remove covers or touch components. A professional assessment determines whether the concern is localized, urgent or connected to a broader panel condition issue.'),
      @('Preparing for Several Electric Loads in Plano','<strong>Representative scenario:</strong> The household expects an EV, electric cooking and future storage. Reviewing the planned loads together helps establish whether the service and panel can support a staged approach or need a broader upgrade plan.'));
    relatedIntro='Panel capacity can affect solar repairs, storage options and EV charging. Coordinating these services keeps the electrical scope tied to the real project.';
    authority='Panel Space and Electrical Capacity Are Different Questions'; authorityCopy='<p>An empty breaker position does not by itself prove that a service can support a new load, and a crowded panel does not automatically mean the entire service must be replaced. The decision should combine equipment ratings, calculated demand, panel condition and the requirements of the proposed solar, battery or EV equipment.</p>';
    faqTitle='Questions About Electrical Panel Upgrades'; faqLead='What Dallas-Fort Worth owners should clarify before adding solar, storage or charging equipment.';
    qs=@('Does an EV charger always require a panel upgrade?','Can solar or a battery use the last open breaker spaces?','What information is needed to assess panel capacity?','Should I be concerned about heat marks or corrosion?','Can panel work be planned for future electric appliances?');
    ans=@('No. Charger power, existing service capacity, calculated household demand and available connection options all matter. An assessment should determine whether an upgrade, load-management option or different charger setting is appropriate.','Not without confirming the electrical design. Physical space, service capacity, bus and breaker ratings, connection rules and the other proposed equipment must be considered together.','Useful information includes panel and main-breaker ratings, recent electrical projects, major appliances, proposed solar or battery details and the EV charger power being considered. A site assessment confirms what the available information cannot.','Yes. Do not remove covers or touch affected components. Visible heat damage, corrosion, unusual sounds or odors deserve prompt professional assessment, and urgent symptoms may require the utility or emergency services.','Yes. Planned EV charging, electric cooking, heat pumps, storage and other loads can be considered in the capacity review so the upgrade is not sized around only the first project.');
    img=6619; imgUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-electrical-panel-upgrades-dfw-ai-01.webp'; hero=6644; heroUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-electrical-panel-upgrades-dfw-ai-01-hero.webp'; alt='Electrician assessing an electrical panel for a Dallas-Fort Worth solar project'
  },
  @{
    key='ev'; post=6641; h1='EV Charger Installs in Dallas-Fort Worth'; intro='A home EV charger install should match the vehicle, daily driving, parking location and electrical capacity. Solar Repair Pros helps Dallas-Fort Worth owners plan practical charging before the circuit and equipment are finalized.';
    eyebrow='EV CHARGER PLANNING'; section='What Shapes a Safe and Useful Home Charging Setup'; lead='The fastest charger is not always the best fit. Available capacity, overnight charging time, cable reach and future vehicle plans all influence the installation.';
    cards=@(
      @('Daily Driving Needs','Typical mileage and overnight parking time help determine whether a lower charging rate already meets the household routine.','fas fa-car-side'),
      @('Panel Capacity','The proposed charger load must be considered with the existing service, major appliances and any planned solar or battery work.','fas fa-bolt'),
      @('Parking and Cable Reach','Charger position, connector reach, trip hazards and how vehicles use the space affect the practical mounting location.','fas fa-route'),
      @('Indoor or Outdoor Location','Weather exposure, equipment rating, impact protection and cable routing matter for garages, carports and exterior parking.','fas fa-house'));
    approachEye='OUR EV CHARGING APPROACH'; approachTitle='EV Charger Planning From the Parking Space Back to the Panel'; approachSub='Match charging power to the property and routine'; approach=@(
      '<strong>Start with the vehicle and schedule:</strong> Connector type, onboard charging limit, daily distance and overnight dwell time define the useful charging target.',
      '<strong>Review the electrical route:</strong> Panel capacity, circuit distance, wall construction and parking layout affect the installation scope.',
      '<strong>Confirm the final equipment:</strong> Charger rating, cable length, indoor or outdoor use and any smart or load-management features should be agreed before installation.');
    trustEye='WHY RIGHT-SIZING MATTERS'; trustTitle='Useful Charging Is About Recovered Range, Not Just Maximum Amps'; trustSub='A practical overnight target may avoid unnecessary electrical work'; trust=@(
      '<strong>Use the vehicle limit:</strong> A charger cannot make the vehicle accept more AC charging power than its onboard equipment allows.',
      '<strong>Plan around available time:</strong> Many drivers can replace normal daily mileage during a long overnight window without the highest circuit rating.',
      '<strong>Keep future changes visible:</strong> A second EV, solar battery or new electric appliance can affect today''s charger and panel decision.');
    scenarios=@(
      @('Garage Charger for a Dallas Commuter','<strong>Representative scenario:</strong> The driver returns home each evening with modest daily mileage. Vehicle charging limits, overnight hours, panel capacity and cable reach are compared before selecting a charger power that meets the routine without automatically maximizing the circuit.'),
      @('Outdoor Charging at a Fort Worth Home','<strong>Representative scenario:</strong> The vehicle parks beside the house rather than in a garage. The plan considers an outdoor-rated charger, mounting surface, weather exposure, impact protection and a cable route that does not create a regular trip hazard.'),
      @('Long Circuit Route at a Plano Property','<strong>Representative scenario:</strong> The panel and parking space are far apart. Route length, wall and ceiling access, conductor requirements and restoration expectations are discussed early because the cable path may influence charger location and total project scope.'),
      @('EV Charger With Future Solar Storage in Frisco','<strong>Representative scenario:</strong> The household expects to add a battery later. Charger power, panel capacity and future storage connection needs are considered together so today''s installation leaves a clearer path for the next project.'));
    relatedIntro='EV charging often connects to panel capacity, solar production and future battery plans. Coordinating the systems can prevent avoidable rework.';
    authority='Home Charging Power Should Match the Vehicle and the Available Time'; authorityCopy='<p>The U.S. Department of Energy''s Alternative Fuels Data Center provides general guidance on <a href="https://afdc.energy.gov/fuels/electricity_charging_home.html" target="_blank" rel="noopener">charging electric vehicles at home</a>. The final charger and circuit still need to match the vehicle, property, equipment instructions and applicable electrical requirements.</p>';
    faqTitle='Questions About EV Charger Installs'; faqLead='Practical answers before choosing home charging equipment in Dallas-Fort Worth.';
    qs=@('How much charging power do I need at home?','Can I use the portable charger that came with the vehicle?','Will I need an electrical panel upgrade?','Where should the EV charger be mounted?','Can an EV charger work with solar panels or a home battery?');
    ans=@('Start with daily mileage, the vehicle''s onboard AC charging limit and the hours normally available overnight. The useful target is enough recovered range for the routine, with capacity and future needs also considered.','Possibly. Portable equipment must be used with a suitable outlet and according to its instructions. Regular high-power charging from an outlet deserves careful assessment of the circuit, outlet condition and intended duty.','Not always. Existing service capacity, household loads, charger setting and possible load-management options all affect the answer. The panel should be assessed before the charger circuit is finalized.','Choose a position that gives reliable connector reach without creating trip hazards or straining the cable. Weather exposure, impact protection, mounting surface, parking habits and the route back to the panel also matter.','Yes, but integration expectations need care. Solar production does not automatically guarantee direct daytime charging, and battery capacity may be better reserved for other loads. The systems should be planned around the owner''s priorities and equipment capabilities.');
    img=6620; imgUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-ev-charger-installs-dfw-ai-01.webp'; hero=6645; heroUrl='https://dev2.mynewwebsite.co.za/wp-content/uploads/2026/06/solar-repair-pros-ev-charger-installs-dfw-ai-01-hero.webp'; alt='Home EV charger installation planned in Dallas-Fort Worth'
  }
)

foreach($s in $services){
  $image = @{id=$s.img;url=$s.imgUrl;alt=$s.alt;source='library';size='full'}
  $heroImage = @{id=$s.hero;url=$s.heroUrl;alt=$s.alt;source='library';size='full'}
  $ops = [System.Collections.Generic.List[object]]::new()
  function AddOp($id,$settings){$ops.Add(@{element_id=$id;settings=$settings})}
  AddOp '426151a' @{background_image=$heroImage;background_video_fallback=$heroImage;background_video_link='';background_slideshow_gallery=@();background_overlay_opacity=@{unit='px';size=0.48};background_position='center center'}
  AddOp '845ddcb' @{background_image=$heroImage;background_video_fallback=$heroImage}
  AddOp 'edce08a' @{background_image=$image;background_video_fallback=$image}
  AddOp '07c6f57' @{title=$s.h1}; AddOp '6810313' @{editor="<p>$($s.intro)</p>"}; AddOp 'c66162b' @{icon_list=@(@{text='Clear Advice';_id='h1'})}; AddOp 'f1dec97' @{icon_list=@(@{text='Practical Planning';_id='h2'})}; AddOp '151ce4e' @{image=$logo}
  AddOp 'f864297' @{title=$s.eyebrow}; AddOp 'df3f8b8' @{title=$s.section}; AddOp 'fff0ad9' @{editor="<p>$($s.lead)</p>"}
  $cardIds=@('e34d257','f67904a','02101ed','b544e88'); for($i=0;$i-lt4;$i++){AddOp $cardIds[$i] @{title_text=$s.cards[$i][0];description_text=$s.cards[$i][1];selected_icon=@{value=$s.cards[$i][2];library='fa-solid'};primary_color=$orange;secondary_color=$light}}
  AddOp '49baa99' @{title=$s.approachEye}; AddOp 'd1698b0' @{title=$s.approachTitle}; AddOp '06300a9' @{title=$s.approachSub}; AddOp '3b110dd' @{icon_list=@(@{text=$s.approach[0];selected_icon=@{value='fas fa-check';library='fa-solid'};_id='a1'},@{text=$s.approach[1];selected_icon=@{value='fas fa-check';library='fa-solid'};_id='a2'},@{text=$s.approach[2];selected_icon=@{value='fas fa-check';library='fa-solid'};_id='a3'})}; AddOp '2bff9b5' @{image=$image}
  AddOp '8b2d19f' @{title=$s.trustEye}; AddOp '7872ddb' @{title=$s.trustTitle}; AddOp '0cab69f' @{title=$s.trustSub}; AddOp 'a7c8c10' @{icon_list=@(@{text=$s.trust[0];selected_icon=@{value='fas fa-check';library='fa-solid'};_id='t1'},@{text=$s.trust[1];selected_icon=@{value='fas fa-check';library='fa-solid'};_id='t2'},@{text=$s.trust[2];selected_icon=@{value='fas fa-check';library='fa-solid'};_id='t3'})}; AddOp 'dc27b4e' @{image=$image}
  AddOp 'd23f129' @{title='REPRESENTATIVE SCENARIOS'}; AddOp 'af9045d' @{title="Common $($s.h1.Replace(' in Dallas-Fort Worth','')) Situations Across Dallas-Fort Worth"}; AddOp 'db3259a' @{editor='<p>These examples describe plausible project situations, not claimed customer jobs. They show how property conditions and customer priorities can change the recommended next step.</p>'}; $storyIds=@('6f2ddbb','93107df','dc9463b','fe1841a'); for($i=0;$i-lt4;$i++){AddOp $storyIds[$i] @{editor="<h4>$($s.scenarios[$i][0])</h4><p>$($s.scenarios[$i][1])</p>"}}
  AddOp '6b5ea5f' @{title='RELATED SERVICES'}; AddOp 'a960571' @{title='Connected Solar and Electrical Services'}; AddOp 'c60f4f6' @{editor="<p>$($s.relatedIntro)</p>"}; AddOp '68e12ad' @{editor='<p>Explore all <a href="/services/">Solar Repair Pros services</a>, review the <a href="/service-areas/">Dallas-Fort Worth service areas</a>, or return to the <a href="/">Solar Repair Pros home page</a>.</p>'}
  AddOp 'e9213de' @{title='GOOD TO KNOW'}; AddOp 'aa7ed50' @{title=$s.authority}; AddOp '97224d4' @{editor=$s.authorityCopy}
  AddOp 'ef0aa27' @{title="$($s.h1.Replace(' in Dallas-Fort Worth','').ToUpper()) FAQS"}; AddOp '8853888' @{title=$s.faqTitle}; AddOp 'da76cdb' @{editor="<p>$($s.faqLead)</p>"}; AddOp '9e71dff' @{items=@(@{_id='f1';item_title=$s.qs[0]},@{_id='f2';item_title=$s.qs[1]},@{_id='f3';item_title=$s.qs[2]},@{_id='7d684a7';item_title=$s.qs[3]},@{_id='899ef6f';item_title=$s.qs[4]});normal_title_color='#000000';accordion_border_normal_color=$orange;accordion_background_hover_color='#15325E';accordion_background_active_color='#15325E';normal_icon_color=$orange;content_background_color=$light;content_border_color=$orange}; $ansIds=@('f068b57','9e2a321','4306533','3728834','620162a'); for($i=0;$i-lt5;$i++){AddOp $ansIds[$i] @{editor="<p>$($s.ans[$i])</p>"}}
  AddOp 'e43168f' @{text='Email Us';link=@{url='mailto:info@solarrepairdfw.com';is_external='';nofollow='';custom_attributes=''}}; AddOp '8e00699' @{text='804-928-2768';link=@{url='tel:+18049282768';is_external='';nofollow='';custom_attributes=''}}; AddOp 'e0f3500' @{text='View All Services';link=@{url='https://dev2.mynewwebsite.co.za/services/';is_external='';nofollow='';custom_attributes=''}}; AddOp '1a3ce4c' @{text='804-928-2768';link=@{url='tel:+18049282768';is_external='';nofollow='';custom_attributes=''}}
  $req=@{jsonrpc='2.0';id=(300+$s.post);method='tools/call';params=@{name='elementor-mcp-batch-update';arguments=@{post_id=$s.post;operations=$ops}}}
  $json = $req | ConvertTo-Json -Depth 20 -Compress
  [IO.File]::WriteAllText((Join-Path $outDir "update-service-$($s.key)-copy-request.json"), $json, [Text.UTF8Encoding]::new($false))
}
